repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml

template:
  org: nf-core
  name: hlarnaseq
  description: Precise analysis of human HLA RNASeq data by usign personalized references
  author: Gennadii Zakharov
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - multiqc
    - fastqc
    - gpu
  is_nfcore: true
