#!/bin/sh

SCRIPT_DIR="${TESTDATA_MAKE_DIR:-$(pwd)}"
DATA_DIR="${SCRIPT_DIR}/data"

REFERENCE_DIR="${DATA_DIR}/reference"
WGS_DIR="${DATA_DIR}/wgs"
HLA_DIR="${DATA_DIR}/hla"

REFERENCE_BASE_URL="http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome"
REFERENCE_FASTA_NAME="GRCh38_full_analysis_set_plus_decoy_hla.fa"
REFERENCE_FAI_NAME="${REFERENCE_FASTA_NAME}.fai"
REFERENCE_FASTA="${REFERENCE_DIR}/${REFERENCE_FASTA_NAME}"
REFERENCE_FAI="${REFERENCE_DIR}/${REFERENCE_FAI_NAME}"

NA12878_BASE_URL="ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239334"
NA12878_CRAM_NAME="NA12878.final.cram"
NA12878_CRAI_NAME="${NA12878_CRAM_NAME}.crai"
NA12878_CRAM="${WGS_DIR}/${NA12878_CRAM_NAME}"
NA12878_CRAI="${WGS_DIR}/${NA12878_CRAI_NAME}"

DEFAULT_HLA_REGION="chr6:28510120-33480577"
DEFAULT_THREADS="2"
REGION="${HLA_REGION:-${DEFAULT_HLA_REGION}}"
THREADS="${THREADS:-${DEFAULT_THREADS}}"

HLA_BAM="${HLA_DIR}/NA12878.chr6_hla.GRCh38.bam"
HLA_BAI="${HLA_BAM}.bai"
HLA_TMP_BAM="${HLA_BAM}.tmp"

RNA_FASTQ_ROOT="${RNA_FASTQ_ROOT:-${SCRIPT_DIR}/gm12878_rnaseq_fastq/fastq}"
RNA_DIR="${DATA_DIR}/rna"
RNASEQ_SAMPLESHEET="${RNASEQ_SAMPLESHEET:-${RNA_DIR}/rnaseq_samplesheet.csv}"
RNASEQ_OUTDIR="${RNASEQ_OUTDIR:-${RNA_DIR}/nf-core-rnaseq}"
RNASEQ_WORKDIR="${RNASEQ_WORKDIR:-${RNA_DIR}/work}"
RNA_HLARNASEQ_DIR="${DATA_DIR}/rna_hlarnaseq"
RNA_HLARNASEQ_MANIFEST="${RNA_HLARNASEQ_MANIFEST:-${RNA_HLARNASEQ_DIR}/rna_samples.csv}"
RNA_HLA_BAM_DIR="${RNA_HLA_BAM_DIR:-${RNA_HLARNASEQ_DIR}/hla_bam}"
