#!/bin/sh

SCRIPT_DIR="${TESTDATA_MAKE_DIR:-$(pwd)}"
DATA_DIR="${SCRIPT_DIR}/data"

REFERENCE_DIR="${DATA_DIR}/reference"
WGS_DIR="${DATA_DIR}/wgs"
HLA_DIR="${DATA_DIR}/hla"

GENCODE_RELEASE="${GENCODE_RELEASE:-50}"
GENCODE_BASE_URL="https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_${GENCODE_RELEASE}"
GENCODE_FASTA_GZ_NAME="GRCh38.primary_assembly.genome.fa.gz"
GENCODE_GTF_GZ_NAME="gencode.v${GENCODE_RELEASE}.primary_assembly.annotation.gtf.gz"
GENCODE_FASTA_GZ="${REFERENCE_DIR}/${GENCODE_FASTA_GZ_NAME}"
GENCODE_GTF_GZ="${REFERENCE_DIR}/${GENCODE_GTF_GZ_NAME}"
GENCODE_REFERENCE_FASTA="${REFERENCE_DIR}/${GENCODE_FASTA_GZ_NAME%.gz}"
GENCODE_REFERENCE_FAI="${GENCODE_REFERENCE_FASTA}.fai"

NA12878_BASE_URL="ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR323/ERR3239334"
NA12878_CRAM_NAME="NA12878.final.cram"
NA12878_CRAI_NAME="${NA12878_CRAM_NAME}.crai"
NA12878_CRAM="${WGS_DIR}/${NA12878_CRAM_NAME}"
NA12878_CRAI="${WGS_DIR}/${NA12878_CRAI_NAME}"

HLA_REGION="chr6:28510120-33480577"
THREADS="2"

HLA_BAM="${HLA_DIR}/NA12878.chr6_hla.GRCh38.bam"
HLA_BAI="${HLA_BAM}.bai"
HLA_TMP_BAM="${HLA_BAM}.tmp"

RNA_DIR="${DATA_DIR}/rna"
RNA_DOWNLOAD_DIR="${DATA_DIR}/gm12878_rnaseq_fastq"
RNA_FASTQ_ROOT="${RNA_DOWNLOAD_DIR}/fastq"
RNASEQ_SAMPLESHEET="${RNA_DIR}/rnaseq_samplesheet.csv"
RNASEQ_OUTDIR="${RNA_DIR}/nf-core-rnaseq"
RNASEQ_WORKDIR="${RNA_DIR}/work"
RNA_HLARNASEQ_DIR="${DATA_DIR}/rna_hlarnaseq"
RNA_HLARNASEQ_MANIFEST="${RNA_HLARNASEQ_DIR}/rna_samples.csv"
RNA_HLA_BAM_DIR="${RNA_HLARNASEQ_DIR}/hla_bam"
